# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-24 14:18
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='created_at',
            field=models.DateTimeField(auto_now=True, default=datetime.datetime(2016, 5, 24, 14, 17, 41, 289039, tzinfo=utc)),
            preserve_default=False,
        ),
    ]
