# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-03 15:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_auto_20160528_1839'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='image',
            field=models.ImageField(blank=True, upload_to='image/profile/'),
        ),
    ]
