# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-05 05:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0005_auto_20160604_0058'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='name',
            field=models.CharField(default='a', max_length=20),
            preserve_default=False,
        ),
    ]
