# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-05 15:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('canape', '0004_auto_20160606_0048'),
    ]

    operations = [
        migrations.AlterField(
            model_name='canape',
            name='quantity',
            field=models.IntegerField(default=0),
        ),
    ]
