# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-13 10:40
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('canape', '0006_auto_20160613_1923'),
    ]

    operations = [
        migrations.AlterField(
            model_name='code',
            name='gainer',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
