# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-24 14:18
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('postage', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Code',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=16)),
                ('serial', models.IntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('gainer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='postage',
            name='maker',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='postage',
            name='image',
            field=models.ImageField(upload_to='image/postage/'),
        ),
        migrations.AddField(
            model_name='code',
            name='postage',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='postage.Postage'),
        ),
    ]
