# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-31 23:31
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('postage', '0002_auto_20160524_2318'),
    ]

    operations = [
        migrations.AddField(
            model_name='code',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, default=datetime.datetime(2016, 5, 31, 23, 31, 11, 986067, tzinfo=utc)),
            preserve_default=False,
        ),
    ]
